version: '2'
services:
  trustedbot:
    build: .
    ports:
      - "9229:9229"
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
    volumes:
      - ./scripts:/opt/scripts
      - ./bin:/opt/bin
      - ./process.env:/opt/process.env
    stdin_open: true
    tty: true
    links:
      - redis
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
